version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp_password
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  webapi:
    build:
      context: .
      dockerfile: ChatApp.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=chatapp;Username=chatapp;Password=chatapp_password
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./chatapp-web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_CHAT_APP_API_URL=http://localhost:5000
    depends_on:
      - webapi

volumes:
  postgres_data: 